import type { Metadata } from 'next'
import { Red_Hat_Text } from 'next/font/google'
import '@/styles/globals.css'

const redHatText = Red_Hat_Text({ subsets: ['latin'], weight: ['400', '600', '700'] })

export const metadata: Metadata = {
	title: 'Product List with Cart',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={redHatText.className}>{children}</body>
		</html>
	)
}
